name: Check for new Terraform release

on:
  schedule:
    - cron: '0 0 * * */7'
  workflow_dispatch:

jobs:
  check-release:
    runs-on: ubuntu-20.04
    
    outputs:
      latest-release: ${{ steps.latest.outputs.LATEST_RELEASE }}
      current-release: ${{ steps.current.outputs.CURRENT_RELEASE }}

    steps:
      - uses: actions/checkout@v2

      - name: Get latest Terraform release
        id: latest
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl
          
          TF_LATEST=$(curl -s https://api.github.com/repos/hashicorp/terraform/releases/latest | grep tag_name | cut -d '"' -f4)
          echo '::set-output name=LATEST_RELEASE::'$TF_LATEST
          echo "Latest Terraform version: "$TF_LATEST
          
      - name: Get current Terraform release for Power
        id: current
        run: |
          TF_CURRENT=$(curl -s https://api.github.com/repos/ppc64le-development/terraform-ppc64le/releases/latest | grep tag_name | cut -d '"' -f4)
          echo '::set-output name=CURRENT_RELEASE::'$TF_CURRENT
          echo "Current Terraform version on Power: "$TF_CURRENT
          
  build-new-release:
    if: ${{ needs.check-release.outputs.latest-release }} != ${{ needs.check-release.outputs.current-release }}
    uses: ./.github/workflows/build_terraform.yml